# Generated by Django 4.2.25 on 2025-12-22 04:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('PIN', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Current Account',
                'verbose_name_plural': 'Current Accounts',
            },
        ),
        migrations.CreateModel(
            name='BankPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funds', models.DecimalField(decimal_places=2, default=9999999999999, max_digits=15)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Tickets',
            fields=[
                ('user_id', models.IntegerField(unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(choices=[('transaction', 'Transaction'), ('account', 'Account'), ('card', 'Card'), ('loan', 'Loan'), ('other', 'Other')], max_length=255)),
                ('complaint', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('user_id', models.IntegerField(unique=True)),
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Loan ID', primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('monthly_repayment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to_repay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('duration', models.CharField(choices=[('1 Month', '1 Month'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('24 Months', '24 Months')], default='1 Month', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('loan_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('paid_off', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('card_number', models.CharField(max_length=128, unique=True)),
                ('card_type', models.CharField(choices=[('debit', 'Debit')], default='debit', max_length=10)),
                ('expiration_date', models.DateField(default=datetime.datetime(2028, 12, 21, 5, 3, 0, 136155))),
                ('cvv', models.CharField(max_length=255, unique=True)),
                ('PIN', models.CharField(max_length=255, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_service.bankaccount')),
            ],
        ),
    ]
