# Generated by Django 4.2.25 on 2025-12-04 23:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.UUIDField(blank=True, help_text='UUID from Ledger Service', unique=True)),
                ('user_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('debit', 'Debit')], default='debit', max_length=10)),
                ('expiration_date', models.DateField(default=datetime.datetime(2028, 12, 4, 0, 58, 49, 574782))),
                ('cvv', models.CharField(max_length=4)),
                ('PIN', models.CharField(max_length=128)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('PIN', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Current Account',
                'verbose_name_plural': 'Current Accounts',
            },
        ),
        migrations.CreateModel(
            name='IT_Tickets',
            fields=[
                ('user_id', models.IntegerField(unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('complaint', models.TextField()),
                ('taken', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('user_id', models.IntegerField(unique=True)),
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Loan ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('duration', models.CharField(choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('24 Months', '24 Months')], default='3 Months', max_length=15)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('loan_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('paid_off', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('PIN', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Savings Account',
                'verbose_name_plural': 'Savings Accounts',
            },
        ),
    ]
