# Generated by Django 4.2.25 on 2025-12-22 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 12, 21, 20, 23, 31, 113233)),
        ),
    ]
