# Generated by Django 4.2.25 on 2025-12-05 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ledger_id',
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 12, 4, 1, 32, 7, 90191)),
        ),
    ]
