# Generated by Django 4.2.25 on 2025-12-10 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0002_remove_account_ledger_id_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 12, 9, 12, 3, 55, 68190)),
        ),
    ]
