# Generated by Django 4.2.25 on 2025-12-10 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0003_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='current_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_service.currentaccount'),
        ),
        migrations.AddField(
            model_name='card',
            name='savings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_service.savingsaccount'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 12, 9, 12, 4, 12, 422745)),
        ),
    ]
