# Generated by Django 4.2.25 on 2025-12-22 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0003_alter_card_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='savings_account',
            new_name='bank_account',
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 12, 21, 20, 31, 42, 334960)),
        ),
    ]
