# Generated by Django 4.2.25 on 2025-12-11 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0004_card_current_account_card_savings_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 12, 10, 23, 52, 19, 875762)),
        ),
    ]
