# Generated by Django 4.2.25 on 2025-12-11 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0005_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_to_repay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 12, 10, 23, 54, 7, 216795)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
