# Generated by Django 4.2.25 on 2025-12-11 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0006_loan_amount_to_repay_alter_card_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 12, 10, 23, 54, 20, 575446)),
        ),
    ]
