# Generated by Django 4.2.25 on 2025-12-11 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_service', '0007_alter_card_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funds', models.DecimalField(decimal_places=2, default=9999999999999, max_digits=15)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 12, 11, 0, 20, 33, 927703)),
        ),
    ]
