# Generated by Django 4.2.25 on 2025-12-22 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID from Identity_service')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('currency', models.CharField(default='NGN', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_account_id', models.IntegerField(help_text='BankAccount number (Account Service)')),
                ('payee_account_id', models.IntegerField(help_text='BankAccount number (Account Service)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('payment_type', models.CharField(choices=[('INTERNAL', 'Internal Transfer'), ('CARD', 'Card Payment'), ('BANK_EXTERNAL', 'External Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
