# Generated by Django 4.2.25 on 2025-12-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='account_number',
        ),
    ]
