# Generated by Django 4.2.25 on 2025-12-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_paymentaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='account_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
