# Generated by Django 4.2.25 on 2025-12-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentaccount_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='balance',
        ),
    ]
