# Generated by Django 4.2.25 on 2025-12-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_paymentaccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='processor_reference',
        ),
    ]
