# payments/Dockerfile
FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r Requirement.txt

COPY . /app/

EXPOSE 8003

CMD ["python", "manage.py", "runserver", "0.0.0.0:8003"]