# Generated by Django 4.2.25 on 2025-12-05 00:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funds', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_id', models.IntegerField(help_text='ID of the User from Identity Service', unique=True)),
                ('account_type', models.CharField(max_length=50)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_id', models.UUIDField(help_text='ID from Loan Service', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.CharField(choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('24 Months', '24 Months')], default='3 Months', max_length=15)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('loan_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('paid_off', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='This helps pin the user initiating the transaction')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reconciled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='This helps pin user initiating the transaction')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('immutable_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.ledgeraccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.transaction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('amount', 0), _negated=True), name='non_zero_amount'),
        ),
    ]
